sudo: required
services:
- docker
os:
- linux
language: python
env:
  matrix:
  - CODENAME="ubuntu:trusty"
  - CODENAME="ubuntu:xenial"
  - CODENAME="ubuntu:bionic"
  global:
  - DEBFULLNAME="Marius van den Beek (travis-ci)"
  - DEBEMAIL="m.vandenbeek@gmail.com"
  - PPA="ppa:galaxyproject/nginx"
install:
- docker pull $CODENAME
script:
- mkdir build
- docker run -v $PWD/build:/host -v $PWD/nginx:/nginx -e DEBFULLNAME="$DEBFULLNAME"
  -e DEBEMAIL="$DEBEMAIL" -e PPA="$PPA" $CODENAME /nginx/build-ubuntu.sh
deploy:
- provider: script
  skip_cleanup: true
  script: docker run -v $PWD/build:/host -v $PWD/nginx:/nginx -v $PWD/launchpad_gpg_key.asc:/gpg_key.asc
    -e DEBFULLNAME="$DEBFULLNAME" -e DEBEMAIL="$DEBEMAIL" -e PPA="$PPA" $CODENAME
    bash /nginx/build-ubuntu.sh
before_install:
- openssl aes-256-cbc -K $encrypted_58e9086bca66_key -iv $encrypted_58e9086bca66_iv
  -in launchpad_gpg_key.asc.enc -out launchpad_gpg_key.asc -d
