---
# Default Starforge config

docker:
    use_sudo: no

qemu:
    qemu_use_sudo: no
    btrfs_use_sudo: no

imagesets:
    purepy-wheel:
        # tag on debian8-wheel
        - starforge/purepy-wheel
    default-wheel:
        - starforge/manylinux1:latest
        - starforge/manylinux1-32:latest
        - starforge/osx-wheel:10.6
    full-wheel:
        - starforge/debian-wheel:6
        - starforge/debian-wheel:7
        - starforge/debian-wheel:8
        - starforge/debian-wheel:stretch
        - starforge/debian32-wheel:6
        - starforge/debian32-wheel:7
        - starforge/debian32-wheel:8
        - starforge/debian32-wheel:stretch
        - starforge/ubuntu-wheel:12.04
        - starforge/ubuntu-wheel:14.04
        - starforge/ubuntu-wheel:15.04
        - starforge/ubuntu-wheel:15.10
        - starforge/ubuntu32-wheel:12.04
        - starforge/ubuntu32-wheel:14.04
        - starforge/ubuntu32-wheel:15.04
        - starforge/ubuntu32-wheel:15.10
        - starforge/centos-wheel:6
        - starforge/centos-wheel:7
        - starforge/centos32-wheel:6
        - starforge/opensuse-wheel:13
        - starforge/fedora-wheel:21
        - starforge/fedora-wheel:22
        - starforge/osx-wheel:10.6
    default_plus_rhel_6-wheel:
        - starforge/base-wheel
        - starforge/base32-wheel
        - starforge/osx-wheel:10.6
        - starforge/centos-wheel:6
        - starforge/centos32-wheel:6

images:
    # default image type is `docker`
    # default pkgtool is `apt`
    # default pythons are `/python/cp*-{os.uname()[4]}`
    starforge/manylinux1:latest:
        pkgtool: yum
        buildpy: /opt/wheelenv/bin/python
        pythons:
            - /python/cp27m-x86_64/bin/python
            - /python/cp27mu-x86_64/bin/python
        plat_name: manylinux1_x86_64
        force_plat: false
        postbuild: for whl in dist/*.whl; do auditwheel repair $whl -w dist; rm $whl; done
    starforge/manylinux1-32:latest:
        pkgtool: yum
        buildpy: /opt/wheelenv/bin/python
        pythons:
            - /python/cp27m-i686/bin/python
            - /python/cp27mu-i686/bin/python
        plat_name: manylinux1_i686
        force_plat: false
        # until https://github.com/pypa/auditwheel/pull/27 is released in the manylinux image
        postbuild: for whl in dist/*.whl; do auditwheel repair $whl -w dist; rm $whl; done; for whl in dist/*-linux_i686.manylinux1__i686.whl; do nwhl=$(echo $whl | sed -e 's/linux_i686.manylinux1__i686/manylinux1_i686/'); echo mv $whl $nwhl; mv $whl $nwhl; done
    starforge/purepy-wheel:
        pythons:
            - /python/cp26mu-{arch}/bin/python
    starforge/base-wheel:
        plat_name: linux_x86_64
    starforge/base32-wheel:
        plat_name: linux_i686
    starforge/centos-wheel:6:
        pkgtool: yum
        plat_name: linux_x86_64_rhel_6
    starforge/centos-wheel:7:
        pkgtool: yum
        plat_name: linux_x86_64_rhel_7
    starforge/centos32-wheel:6:
        pkgtool: yum
        plat_name: linux_i686_rhel_6
    starforge/fedora-wheel:21:
        pkgtool: yum
    starforge/fedora-wheel:22:
        pkgtool: yum
    starforge/opensuse-wheel:13:
        pkgtool: zypper
    starforge/osx-wheel:10.6:
        type: qemu
        pkgtool: brew
        buildpy: /python/wheelenv/bin/python
        pythons:
            - /python/cp26m-{arch}/bin/python
            - /python/cp27m-{arch}/bin/python
        run_cmd: >
            qemu-system-x86_64
            -enable-kvm
            -m {mem}
            {smp}
            -smbios type=2
            -kernel {bootloader}
            -cpu core2duo
            -machine q35
            -usb -device usb-kbd -device usb-mouse
            -vga std
            -vnc none
            -netdev user,id=hub0port0,hostfwd=tcp:127.0.0.1:{sshport}-:22
            -device e1000-82545em,netdev=hub0port0,id=mac_vnet0
        run_args:
            mem: 2048
            smp: -smp 2,cores=2
            bootloader: boot
            drives:
                -file: hd.img
        ssh:
            user: root
            args: '-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -q'
            keyfile: ~/.ssh/id_rsa_osx_wheel_10_6
        snap_root: ~/snapshots
        snap_src: '@starforge-wheel'
        # place osk in $XDG_CONFIG_DIR/galaxy-starforge/osk.txt
        insert_osk: yes
        vvfat_mount_base: /Volumes
