---
# Default Starforge config

docker:
    use_sudo: no

qemu:
    qemu_use_sudo: no
    btrfs_use_sudo: no

imagesets:
    purepy-wheel:
        - starforge/manylinux1:purepy
    default-wheel:
        - starforge/manylinux1:latest
        - starforge/manylinux1-32:latest
        - starforge/osx-wheel:10.6
    linux-wheel:
        - starforge/manylinux1:latest
        - starforge/manylinux1-32:latest
    macos-wheel:
        - starforge/osx-wheel:10.6
    linux32-macos-wheel:
        - starforge/manylinux1-32:latest
        - starforge/osx-wheel:10.6
    full-wheel:
        - starforge/debian-wheel:7
        - starforge/debian-wheel:8
        - starforge/debian-wheel:stretch
        - starforge/debian32-wheel:7
        - starforge/debian32-wheel:8
        - starforge/debian32-wheel:stretch
        - starforge/ubuntu-wheel:14.04
        - starforge/ubuntu-wheel:16.04
        - starforge/ubuntu-wheel:16.10
        - starforge/ubuntu32-wheel:14.04
        - starforge/ubuntu32-wheel:16.04
        - starforge/ubuntu32-wheel:16.10
        - starforge/centos-wheel:6
        - starforge/centos-wheel:7
        - starforge/centos32-wheel:6
        - starforge/fedora-wheel:23
        - starforge/fedora-wheel:24
        - starforge/fedora-wheel:25
        - starforge/opensuse-wheel:13
        - starforge/opensuse-wheel:42
        - starforge/osx-wheel:10.6

images:
    # default image type is `docker`
    # default pkgtool is `apt`
    # default pythons are `/python/cp*-{os.uname()[4]}`
    starforge/manylinux1:latest:
        pkgtool: yum
        buildpy: /opt/wheelenv/bin/python
        pythons:
            - /opt/python/cp27-cp27m/bin/python
            - /opt/python/cp27-cp27mu/bin/python
            - /opt/python/cp34-cp34m/bin/python
            - /opt/python/cp35-cp35m/bin/python
            - /opt/python/cp36-cp36m/bin/python
        plat_name: manylinux1_x86_64
        force_plat: false
        use_auditwheel: true
    starforge/manylinux1-32:latest:
        pkgtool: yum
        buildpy: /opt/wheelenv/bin/python
        pythons:
            - /opt/python/cp27-cp27m/bin/python
            - /opt/python/cp27-cp27mu/bin/python
            - /opt/python/cp34-cp34m/bin/python
            - /opt/python/cp35-cp35m/bin/python
            - /opt/python/cp36-cp36m/bin/python
        plat_name: manylinux1_i686
        force_plat: false
        use_auditwheel: true
    starforge/manylinux1:purepy:
        buildpy: /opt/wheelenv/bin/python
        pythons:
            - /opt/python/cp27-cp27m/bin/python
            - /opt/python/cp36-cp36m/bin/python
    starforge/debian-wheel:7:
        plat_specific: true
    starforge/debian-wheel:8:
        plat_specific: true
    starforge/debian-wheel:stretch:
        plat_specific: true
    starforge/debian32-wheel:7:
        plat_specific: true
    starforge/debian32-wheel:8:
        plat_specific: true
    starforge/debian32-wheel:stretch:
        plat_specific: true
    starforge/ubuntu-wheel:14.04:
        plat_specific: true
    starforge/ubuntu-wheel:16.04:
        plat_specific: true
    starforge/ubuntu-wheel:16.10:
        plat_specific: true
    starforge/ubuntu32-wheel:14.04:
        plat_specific: true
    starforge/ubuntu32-wheel:16.04:
        plat_specific: true
    starforge/ubuntu32-wheel:16.10:
        plat_specific: true
    starforge/centos-wheel:6:
        pkgtool: yum
        plat_name: linux_x86_64_rhel_6
        plat_specific: true
    starforge/centos-wheel:7:
        pkgtool: yum
        plat_name: linux_x86_64_rhel_7
        plat_specific: true
    starforge/centos32-wheel:6:
        pkgtool: yum
        plat_name: linux_i686_rhel_6
        plat_specific: true
        plat_specific: true
    starforge/fedora-wheel:23:
        pkgtool: yum
        plat_specific: true
    starforge/fedora-wheel:24:
        pkgtool: yum
        plat_specific: true
    starforge/fedora-wheel:25:
        pkgtool: yum
        plat_specific: true
    starforge/opensuse-wheel:13:
        pkgtool: zypper
        plat_specific: true
    starforge/opensuse-wheel:42:
        pkgtool: zypper
        plat_specific: true
    starforge/osx-wheel:10.6:
        type: qemu
        pkgtool: brew
        buildpy: /python/wheelenv/bin/python
        pythons:
            - /python/cp27m-{arch}/bin/python
        plat_name: macosx_10_6_intel
        use_delocate: true
        run_cmd: >
            qemu-system-x86_64
            -enable-kvm
            -m {mem}
            {smp}
            -smbios type=2
            -kernel {bootloader}
            -cpu core2duo
            -machine q35
            -usb -device usb-kbd -device usb-mouse
            -vga std
            -vnc none
            -netdev user,id=hub0port0,hostfwd=tcp:127.0.0.1:{sshport}-:22
            -device e1000-82545em,netdev=hub0port0,id=mac_vnet0
        run_args:
            mem: 2048
            smp: -smp 2,cores=2
            bootloader: boot
            drives:
                - file: hd.img
        ssh:
            user: root
            args: '-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -q'
            keyfile: ~/.ssh/id_rsa_osx_wheel_10_6
        snap_root: ~/snapshots
        snap_src: '@starforge'
        # place osk in $XDG_CONFIG_DIR/galaxy-starforge/osk.txt
        insert_osk: yes
        vvfat_mount_base: /Volumes
